name: 🚧 Integration
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  format:
    name: 💅 Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm prettier --check .

  generateVideos:
    needs:
      - format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composition:
          - name: "Monogram"

    name: 📽 Generating ${{matrix.composition.name}}
    steps:
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(matrix.event.inputs) }}
      - run: pnpm remotion render src/index.ts ${{matrix.composition.name}} out/${{matrix.composition.name}}.mp4
      - uses: actions/upload-artifact@v3
        with:
          name: video
          path: out

  nextjs:
    name: ⚛️ NextJS application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
